### ISSUE TITLE
Token isnt saved between page reload

### ISSUE THREAD

**Issue by BjornMelgaard** [Sly777/ran#102]
maybe save it in cookie?

**Comment by Sly777** [comment]
I realized that yesterday, too. Right now, We are saving the data with ```dispatchers.signIn``` ```components/AuthFields/index.data.js:43``` so that means save is working but It's not working anymore after refreshing the page. We need to trigger the **checkToken** on every refresh (first load)

**Comment by BjornMelgaard** [comment]
as I know, localForage is intended to use in client-side, but we need token on server-side too, its better to use cookie
