### ISSUE TITLE
Directory structure

### ISSUE THREAD

**Issue by srghma** [Sly777/ran#106]
I suggest 
```
 ~/projects/ran   jest  tree -L 1 --dirsfirst pages components containers libraries libraries/stores components/AuthFields
pages
├── create.js
├── details.js
├── _document.js
├── index.js
├── signin.js
└── signup.js
components
├── AuthFields
├── LinkList
└── Theme.js
containers
├── CreatePost
├── Header
├── PostInfo
├── PostList
├── PostUpvoter
├── SignInForm
├── SignUpForm
├── App.js
└── Default.js
libraries
├── graphql_schemas
├── stores
├── apolloClient.js
├── helpers.js
├── middleware.js
├── persist.js
├── redirect.js
├── reducer.js
├── reduxStore.js
├── theme.js
├── validations.js
└── withData.js
libraries/stores
└── auth.js
components/AuthFields
├── index.js
├── styles.js
└── validation.js
```

1. If component is using data from apollo or redux - its container
2. Locate stores (reducers, actions,...) separately from components/containers ( `libraries/stores` or  `libraries/modules`)

@Sly777 you said you have some concerns

**Comment by BjornMelgaard** [comment]
Also I dont like when components consist of 
1. data.js - which export function `connect` which is wrapper that connect components to store or apollo
2. index.js - component actually and in the end `export default connect(Component)`

better
1. feature.js - component, not yet attached to data (also can split feature to feature(smart) and presentation(dumb))
2. index.js - import feature and attach it to data

Why? for testing, first example force us to test component attached to data, with second we have option to test component only or component with data
