### ISSUE TITLE
Error: Cannot find module 'webpack-bundle-analyzer'

### ISSUE THREAD

**Issue by zinsai** [Sly777/ran#107]
Hello, Deploy to Heroku is failing with 

remote: Error: Cannot find module 'webpack-bundle-analyzer'
remote:     at Function.Module._resolveFilename (module.js:470:15)
remote:     at Function.Module._load (module.js:418:25)
remote:     at Module.require (module.js:498:17)
remote:     at require (internal/module.js:20:19)
remote:     at Object.<anonymous> (/tmp/build_65f4de2af172386a65e33f4f3fb39125/next.config.js:1:96)
remote:     at Module._compile (module.js:571:32)
remote:     at Object.Module._extensions..js (module.js:580:10)
remote:     at Module.load (module.js:488:32)
remote:     at tryModuleLoad (module.js:447:12)
remote:     at Function.Module._load (module.js:439:3)
remote: npm ERR! code ELIFECYCLE
remote: npm ERR! errno 1
remote: npm ERR! ran-boilerplate@0.4.0 heroku-postbuild: `next build`
remote: npm ERR! Exit status 1
remote: npm ERR! 
remote: npm ERR! Failed at the ran-boilerplate@0.4.0 heroku-postbuild script.
remote: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
remote: 
remote: npm ERR! A complete log of this run can be found in:
remote: npm ERR!     /app/.npm/_logs/2017-08-11T16_46_07_571Z-debug.log
remote: { Error: Cannot find module 'webpack-bundle-analyzer'
remote:     at Function.Module._resolveFilename (module.js:470:15)
remote:     at Function.Module._load (module.js:418:25)
remote:     at Module.require (module.js:498:17)
remote:     at require (internal/module.js:20:19)
remote:     at Object.<anonymous> (/tmp/build_65f4de2af172386a65e33f4f3fb39125/next.config.js:1:96)
remote:     at Module._compile (module.js:571:32)
remote:     at Object.Module._extensions..js (module.js:580:10)
remote:     at Module.load (module.js:488:32)
remote:     at tryModuleLoad (module.js:447:12)
remote:     at Function.Module._load (module.js:439:3) code: 'MODULE_NOT_FOUND' }
remote: 
remote: -----> Build failed
remote:        
remote:        We're sorry this build is failing! You can troubleshoot common issues here:
remote:        https://devcenter.heroku.com/articles/troubleshooting-node-deploys
remote:        
remote:        If you're stuck, please submit a ticket so we can help:
remote:        https://help.heroku.com/
remote:        
remote:        Love,
remote:        Heroku

Please guide. Thank you.

**Comment by Sly777** [comment]
hey @zinsai, I fixed this on the new version. Please check and if you have still problem, we can open the issue again :)
