### ISSUE TITLE
.eslintrc formatting

### ISSUE THREAD

**Issue by spences10** [Sly777/ran#113]
Quote formatting needs changing on `.eslintrc` singles instead of double:

https://github.com/Sly777/ran/blob/c91c9366fe35a84ff10e3697cb06d091014100fe/.eslintrc#L45-L46

Should be:

```json
    "graphql/template-strings": ["error", {
      "env": "literal"
    }]
```

**Comment by Sly777** [comment]
@spences10, I fixed it on the beta branch. I will merge it tomorrow I guess.
