### ISSUE TITLE
bug, styled-comp, checksum was invalid on page reload

### ISSUE THREAD

**Issue by srghma** [Sly777/ran#120]
What I do
1. yarn run dev
2. load page
3. reload page

Get error

```
Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) ="1"><div class="sc-bdVaJa iNGvMq" data-
 (server) ="1"><div class="sc-jzJRlG fzsTbP" data-

```

related https://github.com/styled-components/babel-plugin-styled-components/issues/52

will look tomorrow

**Comment by bliitzkrieg** [comment]
I'm also experiencing this issue - Update here with your finding if you can! :)

**Comment by BjornMelgaard** [comment]
@bliitzkrieg can you create pull request with your solution to ran?

**Comment by bliitzkrieg** [comment]
@BjornMelgaard I'm not using ran and my code is IP for my company but the fix for me was putting the `styled-components` stuff in both environments.

"next: "3.0.6",
"styled-components": "2.1.2",
"babel-plugin-styled-components": "1.1.7"


```
{
  "env": {
    "development": {
      "presets": "next/babel",
      "plugins": [
        ["styled-components", {
          "ssr": true,
          "displayName": true,
          "preprocess": false
        }]
      ]
    },
    "production": {
      "presets": "next/babel",
      "plugins": [
        ["styled-components", {
          "ssr": true,
          "displayName": true,
          "preprocess": false
        }]
      ]
    },
    "test": {
      "presets": [
        ["env", { "modules": "commonjs" }],
        "next/babel"
      ]
    }
  }
}
```

**Comment by BjornMelgaard** [comment]
@bliitzkrieg hm, [didnt help](https://github.com/BjornMelgaard/ran/blob/styled-components-reload-fix/.babelrc), still error on reload, seems like you changed all `styled.extend` to `styled(Comp)` and with change in bablerc it helped, no?

**Comment by BjornMelgaard** [comment]
https://github.com/styled-components/babel-plugin-styled-components/issues/79

**Comment by bliitzkrieg** [comment]
I never used `styled.extend` in my application

**Comment by Sly777** [comment]
Hey all, It's fixed after some changes on "styled components" plugin and also the integration of new extend functionality of "styled components". I'm closing now. Please inform me if it still continues on your system.
