### ISSUE TITLE
Cached .gql files not reloading on change

### ISSUE THREAD

**Issue by GreatScot** [Sly777/ran#126]
Hi, I am not totally sure whether this is a bug (or perhaps something is wrong with my config), but if I load up a component wrapped by Apollo, (which has the graphql code saved in a separate .gql file as this seems to the be the RAN convention at the moment), then the contents of that .gql file appear to be cached somewhere, and will never update again no matter what changes I make to the file (shutting down the server and restarting makes no difference).

The only way I have found to permit changes to the .gql code is to copy it directly into data.js (i.e. instead of import-ing from a .gql file).

Would really appreciate a pointer here - at the moment I am basically refactoring pieces of .gql code into the data.js files so that I can edit them successfully.

Thanks!

**Comment by Sly777** [comment]
Fixed on #136
