### ISSUE TITLE
Component executed twice?

### ISSUE THREAD

**Issue by sheats** [Sly777/ran#130]
I'm a little new to react so forgive me if this is a dumb question.  I used your PostList component as an example and noticed it being executed twice.
I added:

```
index 02cc730..0ca55c6 100644
--- a/shopify-ui/components/PostList.js
+++ b/shopify-ui/components/PostList.js
@@ -8,6 +8,7 @@ import PostUpvoter from './PostUpvoter';
 const POSTS_PER_PAGE = 10;

 let PostList = ({ data: { allPosts, loading, _allPostsMeta }, loadMorePosts, className }) => {
+  console.log(allPosts);
   if (allPosts && allPosts.length) {
     const areMorePosts = allPosts.length < _allPostsMeta.count;
     return (
```

Refreshed / and it prints twice in the server console as well as the browser console.  Is it supposed to do that?

**Comment by Sly777** [comment]
Hey @sheats,

I checked it and yes, it's a bug :) I don't know why but apollo-react is rendering the component two times. I was thinking that's because of the server rendering but It's not. If I find any answer, I will fix.

**Comment by sheats** [comment]
I think it might be related to https://github.com/zeit/next.js/issues/978

**Comment by Sly777** [comment]
I think it's possible to be fixed after updating the Apollo version.

**Comment by Enalmada** [comment]
I tried updating next.js/examples/with-apollo to the latest versions and the issue still seems to remain.  It would be awesome though if we could get RAN updated to the latest Apollo.  That could make it easier to bring in some experts to look into this further as they will probably insist on debugging the issue with the latest version.  Any chance someone who knows what they are doing could update RAN dependencies to keep the momentum going on this amazing project?

**Comment by Enalmada** [comment]
BTW, apparently this is the way it works.  I suspect this issue can be closed.
https://github.com/zeit/next.js/issues/5050#issuecomment-416771851

**Comment by Sly777** [comment]
Thanks all for help! on @Enalmada's comment, basically it says this is the feature of Apollo :) So I'm closing this issue.
