### ISSUE TITLE
graphcool setup

### ISSUE THREAD

**Issue by Dialectician** [Sly777/ran#144]
I was hoping you could share the data schema in SDL syntax, or offer another way to utilize the already integrated Graphcool schema

**Comment by BjornMelgaard** [comment]
hi, @Dialectician , this is schema that I made and that works, the problem that I found with graphcool is that schemas is not shareable, this schema wont work if you copy-paste it to your graphcool cli

```
# projectId: cj6alpbu60z8s0196ryeqngxs
# version: 8

type File implements Node {
  contentType: String!
  createdAt: DateTime!
  id: ID! @isUnique
  name: String!
  secret: String! @isUnique
  size: Int!
  updatedAt: DateTime!
  url: String! @isUnique
}

type Post implements Node {
  createdAt: DateTime!
  id: ID! @isUnique
  title: String!
  updatedAt: DateTime!
  url: String!
  votes: Int @defaultValue(value: 0)
}

type User implements Node {
  createdAt: DateTime!
  email: String @isUnique
  firstName: String!
  id: ID! @isUnique
  lastName: String!
  password: String
  updatedAt: DateTime!
}
```

**Comment by Dialectician** [comment]
The resolve may be found under [https://www.graph.cool/docs/faq/graphql-how-to-download-graphql-sdl-schema-maiv5eekan/](url)
# Download the schema from the server
graphql get-schema
This downloads a GraphQL schema in SDL syntax

**Comment by BjornMelgaard** [comment]
https://github.com/este/este/blob/master/data/project.graphcool

**Comment by Sly777** [comment]
Hi @Dialectician , I updated the schema. You can find the updated one on [libraries/graphql_schemas/schema.graphql](libraries/graphql_schemas/schema.graphql). Is it okay for you?

**Comment by Sly777** [comment]
And also @Dialectician @BjornMelgaard 
I also added Graphcool Schema -> [/libraries/graphql_schemas/Graphcool-simplified.schema](https://github.com/Sly777/ran/blob/master/libraries/graphql_schemas/Graphcool-simplified.schema)
