### ISSUE TITLE
[Question] Secure pages based on token

### ISSUE THREAD

**Issue by juan-manuel-alberro** [Sly777/ran#175]
Hello all,

What will be best practice to secure a page that only can be shown if the user is logged in?
I can check the `auth` store but it won't work on SSR, any **example** or **idea** of how I can achieve this?

Thanks! :smile:

**Comment by dalerka** [comment]
This might be helpful - https://github.com/estrada9166/server-authentication-next.js

**Comment by Sly777** [comment]
hey @juan-manuel-alberro, If you check (LinkList/index.js)[https://github.com/Sly777/ran/blob/master/components/LinkList/index.js], You can see how we use auth on RAN. Actually, It's really easy to use because You just need to send it from page file. And also it supports SSR. :)
