### ISSUE TITLE
Upgrade React Apollo (new apollo client structure)

### ISSUE THREAD

**Issue by Sly777** [Sly777/ran#270]
- Upgrade React Apollo (new Apollo client structure)

On Apollo v2, Most of the parts are changed and also They removed redux integration inside of it.

**Comment by aarondancer** [comment]
Something to note, they’ve remove Redux as the _default_ cache for Apollo. Redux (as well as other stores) can still be used with configuration.

**Comment by lolcoolkat** [comment]
Any update on this?

**Comment by Sly777** [comment]
I'm planning to work on this in couple of weeks but PR's welcome :) @lolcoolkat

**Comment by willopez** [comment]
@Sly777 looking forward to this PR, and thank you for your work.

**Comment by ranleung** [comment]
hi, any update on this? :)

**Comment by Enalmada** [comment]
I am extremely grateful for @Sly77's contribution to the community.  As a new user, this template looks like an amazing place to start containing much that I need to learn about.  Please don't lose momentum on this amazing project.

**Comment by Sly777** [comment]
Hey @willopez & @Enalmada! Honestly, I couldn't continue on this issue because of my new job and other changes. It would be really nice if someone helps me on this :)

**Comment by Enalmada** [comment]
I totally know how that goes!  I hope that someone watching that has some apollo experience would be willing to give back to the community and do this upgrade.   I looked at the upgrade docs and they don't look too bad: https://www.apollographql.com/docs/apollo-server/v2/migration-two-dot.html
(I am currently just evaluating potential tech for upgrading our site and have not actually used any of the RAN tech yet but this template gives me confidence RAN is the way to go and will contribute in the future as I get up to speed)

**Comment by Sly777** [comment]
I was working on this last weekend but I realized the biggest issue is the new local cache feature of Apollo. It doesn't fit redux well and I need to change the structure without redux which nobody wants I think :) I also tried to find redux plugins for this but there is no good option to integrate into RAN. So I stuck a little bit because of redux. I also thought maybe we can use something like this;

```
<Provider store={store}>
  <ApolloProvider client={client}>
     <Component {...props} />
  </ApolloProvider>
</Provider>
```

But in this structure, there are some missing parts between Apollo and Redux.

So it's open for any suggestions.

**Comment by Enalmada** [comment]
Experienced users will struggle emotionally with eliminating redux from their stack but based on my research it might be the right thing to do:

The new apollo is trying to intentionally and conveniently eliminate the cognitive and maintenance overhead of maintaining a separate local store ([link](https://blog.apollographql.com/the-future-of-state-management-dd410864cae2?_ga=2.142552882.1408500351.1536681503-1256945442.1536681503)).   Relay is also going [that direction](https://medium.com/@matt.krick/replacing-redux-with-relay-47ed085bfafe).  I believe users discovering RAN are mostly newer and wanting to learn production best practices and optimizations.  There is no doubt they need to learn a graphql client.   The question experienced users need to try and answer as unemotionally as possible...can the current version of apollo client (and perhaps some [context](https://reactjs.org/docs/context.html)) eliminate the price to learn and maintain redux or do new users still need it?

ReasonReact, what Facebook is migrating their internal production into, comes with the concept of [reducer](https://reasonml.github.io/reason-react/docs/en/state-actions-reducer) built into the language.   The combination of this plus graphql client local store continually improving I believe is going to completely deprecate redux.
