### ISSUE TITLE
What about using next-routes?

### ISSUE THREAD

**Issue by SachaG** [Sly777/ran#36]
I'm brand new to the Next.js world and I'm trying to see what packages everybody uses. I noticed you're not using [next-routes](https://github.com/fridays/next-routes) in this boilerplate. 

I'm just curious to know if this is something you considered? Are there any downsides to using it?

**Comment by Sly777** [comment]
Hey @SachaG, "next-routes" is way better than "next-url-prettifier" (also I contribute to next-routes 😆 ) But When I started to work on RAN!, "next-url-prettifier" was more suitable for all config of RAN!. I'm thinking about it but off course, contributions are warmly welcome! :)

**Comment by SachaG** [comment]
OK, thanks! Just wanted to confirm :) I'm still learning Next but I'll try to contribute when I'm a bit more familiar with everything!

**Comment by Sly777** [comment]
Hey @SachaG, you can use RAN! with next-routes on the new version. :)

https://github.com/Sly777/ran/releases/tag/0.4.0

**Comment by SachaG** [comment]
Really cool thanks!
