### ISSUE TITLE
Warning: Prop `className` did not match.

### ISSUE THREAD

**Issue by lolcoolkat** [Sly777/ran#379]
Getting the following error in the console after running `yarn dev` and loading index page.

`Warning: Prop className did not match. Server: "sc-kfGgVZ XgANw" Client: "sc-kAzzGY iUwkLO"`

![html](https://image.prntscr.com/image/VluRIS0jR-SBZfQG_VdbgA.png)

Look's like the issue is either with styled-components or babel-plugin-styled-components.

Any ideas?

**Comment by Sly777** [comment]
Hey @lolcoolkat, The problem is related to Apollo I guess. It renders on server and client (two times in same call). We discussed this on #130. We can continue in there.
