### ISSUE TITLE
How to debug this?

### ISSUE THREAD

**Issue by monotv** [Sly777/ran#404]
A breakpoint I set a in the Developer Tools do not work, code just runs through. How do I debug this?

**Comment by Sly777** [comment]
Hey @monotv, I think there is no problem on putting a breakpoint to debug the system. I tried it now on Chrome developer tools and It works. can you describe more detailed, please?

**Comment by monotv** [comment]
@Sly777 forgot about this issue, got it working in VSCode now in the mean time :)

I can not remember the steps but I basically used this:

https://github.com/Microsoft/vscode-recipes/tree/master/Next-js

**Comment by Sly777** [comment]
perfect! :) So I closed this for now.
