### ISSUE TITLE
Proposal: use ooth for user identity management

### ISSUE THREAD

**Issue by nmaro** [Sly777/ran#408]
Hi there, I'm the developer of [ooth](https://github.com/nmaro/ooth), a modular user identity management system built on top of passport.js (which, famously, only handles the authentication part, but not the storage of user information part).

You have a nice starter here, but if people want to extend the login functionality with other strategies (e.g. facebook or google login) they are on their own. With ooth they could just plug in another strategy and move. What do you think?

**Comment by Sly777** [comment]
Hey @nmaro, It would be nice actually. The only thing is I don't want to add more library because It will gonna too much for basic project. But I'm preparing plugin system for RAN so theoretically, you can create plugin when it's ready. Unfortunately, I still need time to finish it.

**Comment by nmaro** [comment]
Sounds good, thanks
