### ISSUE TITLE
Adding authentication

### ISSUE THREAD

**Issue by ngocdiep** [Sly777/ran#41]
It would be great if you can add the authentication to this project :) Do you schedule to do it?

**Comment by astenmies** [comment]
Thx for putting this together Ilker. I've been trying to setup authentication, the user logs with no issue, but redux looses its state on page refresh. Any idea/example on how to solve this?

**Comment by Sly777** [comment]
Hey @ngocdiep, This is little bit tricky topic. I'm planning to add this but also I don't want to create "huge-messy-starter-kit" so That's why i cannot give the time for release but you can be sure that I will add this feature to RAN!. :)

Hi @astenmies, fast answer is http://dev.apollodata.com/react/auth.html :) Basically, you need to set your token to session token with ```persist.willSetAccessToken(TOKEN);```. Then, When you refresh the page, RAN! will add your token to header authorization with ```bearer```.

You can check [/libraries/apolloClient.js](https://github.com/Sly777/ran/blob/master/libraries/apolloClient.js) and [/libraries/persist.js](https://github.com/Sly777/ran/blob/master/libraries/persist.js) for details.

**Comment by Sly777** [comment]
Also, links below can help to consider how to add auth system on RAN!.

https://github.com/zeit/next.js/issues/153
https://arunoda.me/blog/ssr-and-server-only-modules
https://dev-blog.apollodata.com/a-guide-to-authentication-in-graphql-e002a4039d1
http://dev.apollodata.com/react/auth.html

**Comment by astenmies** [comment]
@Sly777 thx for your answer, I followed the same process...

Successfully setting the token (cfr console.log) 

`.setItem(persist.ACCESS_TOKEN_KEY, value).then(console.log('ACCESS_TOKEN_KEY', value))`

But nothing gets out of the following:
```
(async () => {
          const token = await persist.willGetSessionToken();
          console.log('apolloClient', token)
          req.options.headers.authorization = token ? `Bearer ${token}` : null;
          next();
        })();
```
Here's the crucial part of SignInFormContainer. Using redux-form.

```
const signInMutation = gql`
  mutation signIn($email: String!, $password: String!) {
    signIn(email: $email, password: $password) {
      token,
      errors {
        key
        value
      }
    }
  }
`;

const SignInWithData = graphql(signInMutation)(SignInFormContainer);

const mapDispatchToProps = (dispatch) => ({
  signInDispatcher(token) {
    persist.willSetAccessToken(token);
  }
});

const SignInWithDataAndState = connect(
  null,
  mapDispatchToProps
)(SignInWithData);

export default SignInWithDataAndState;
```
Any advise? Am I missing something?
Thanks in advance

**Comment by astenmies** [comment]
Oh boy, I finally got it working. Awesome... Shall I open a PR?

**Comment by Sly777** [comment]
It can be perfect! @astenmies :)

**Comment by astenmies** [comment]
Alright, let me double-check on all this, remove the styling and stuff and I'll PR.

**Comment by Sly777** [comment]
cool! Also I was trying some stuff for auth so maybe we can add it to your PR after everything is okay.

**Comment by Sly777** [comment]
--
I'm almost done with CL commands for adding authentication. Please approve or edit my authentication pull request in order to use it as CL template.
by @astenmies 
--

I removed the comment that was on the wrong issue.

I'm on that. I guess, today I will finish my review. Also, I have some changes but we can finish them on your branch then we can merge with RAN.

**Comment by astenmies** [comment]
Awesome! Man your CL is awesome, I really love it. I think I got a pretty cool/compact pattern here for auth CL commands, I'll wait for your commits first. Cheers

**Comment by nmaro** [comment]
Hello everybody! Over the last months I created, and now refined

A generic user accounts library for node.js called ooth: https://github.com/nmaro/ooth
A starter library based on next and ooth together with a minimal boilerplate: https://github.com/nmaro/staart
It features:

Registration with email and password
Login with email or username and password
Account page where you can set your username, change your password, and resend a verification email
Forgot password/reset password pages
Verify email page
A basic GraphQL API linked to a MongoDB (1 file, can be easily removed)
Minimal boilerplate (as much logic as possible is encapsulated in libraries)
Check out a live demo here: http://staart.nmr.io/

I did it mainly for myself for rapid prototyping, to get started quickly with an application with a simple, working accounts system that doesn't rely on external services. I'm quite happy with the results. I intend to keep using and maintaining these libraries, so give it a go if you feel that an established accounts system + UI for node is still missing.

**Comment by Sly777** [comment]
Hey all, I published new version! For more info: https://github.com/Sly777/ran/releases/tag/0.3.0

@ngocdiep @astenmies @nmaro

**Comment by astenmies** [comment]
Great work @Sly777 , I learned things thanks to you and enjoyed the process. I'll join again for other things later on, as I'm having a child soon... Cheers

**Comment by Sly777** [comment]
🍾 🎆 🍾 🎆 🍾 🎆  @astenmies wow, such a happy news!!! Congratulations, mate!! 🍾 🎆 🍾 🎆 🍾 🎆 🍾 🎆

**Comment by ngocdiep** [comment]
It's very very great news even today is the weekend!!  Best thanks for your effort to make it!!!
