### ISSUE TITLE
can't resolve packages

### ISSUE THREAD

**Issue by adekbadek** [Sly777/ran#415]
I'm on node `v8.4.0`, macOS `10.13.3`. After cloning the repo and running `yarn` the following error is thrown:

```
yarn install v1.0.0
[1/6] 🔍  Validating package.json...
[2/6] 🔍  Resolving packages...
error "/whatever/RAN/@f/animate@^1.0.1" doesn't exist.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by Sly777** [comment]
hey @adekbadek, can you try again please? I updated packages and now It should work. I didn't get any problem with same conf.

**Comment by adekbadek** [comment]
Worked, but only after upgrading yarn to `v.1.3.2`

**Comment by Sly777** [comment]
aaah I see. I didn't see your yarn version :) thanks for the info @adekbadek
