### ISSUE TITLE
npm run setup or npm run setup:clean failed

### ISSUE THREAD

**Issue by nukinuki** [Sly777/ran#506]
Step one: git clone
Step two: npm install
Step three: npm run setup:clean

```
> Failed to build
{ Error: (client) ./components/App.js
Module build failed: SyntaxError: /Users/Enot/Work/onlogsystem/microservices/RAN/components/App.js: Unexpected token, expected ";" (11:5)

   9 | let offlineInstalled = false;
  10 |
> 11 | type Props = {
     |      ^
  12 |   children: React.Node,
  13 |   theme?: string
  14 | };
```

MacOS
node v9.2.0
npm v6.1.0

**Comment by jordan-jarolim** [comment]
Solved by 
yarn --ignore-engines && yarn setup

**Comment by Sly777** [comment]
It was about next.js and flow version conflict bug. (https://github.com/zeit/next.js/issues/4614) I fixed it on current version of RAN. To easy fix, please set `@babel/plugin-transform-flow-strip-types` package version to '7.0.0-beta.47'
