### ISSUE TITLE
The menu bar can look better and should be floating.

### ISSUE THREAD

**Issue by unisqu** [Sly777/ran#512]
Can we have css or floating like this instead? Also, dont have to use new modules. just make a simple one that looks like below without adding additional overhead. Can it be done?
https://reactnavigation.org/docs/en/api-reference.html

**Comment by Sly777** [comment]
hi @unisqu, I didn't understand your request and also link that you shared. Can you please give more information?

**Comment by Sly777** [comment]
I closed this issue because I didn't get any answer in 14 days.
