### ISSUE TITLE
[SOLVED] Router expected '/' but got 'index' - build:static_export

### ISSUE THREAD

**Issue by davidsanchez96** [Sly777/ran#516]
Hi!
I got this error Router expected '/' but got 'index' when deploying my app to static host after running yarn build:static_export

this is the actual next.config.js file
```
if (process.env.STATIC_EXPORT) {
  initExport.exportPathMap = function exportPathMap() {
    const routes = {};
    routes['/'] = {
      page: 'index'
    };
}
```

I solved the problem by changing the value of page key

```
if (process.env.STATIC_EXPORT) {
  initExport.exportPathMap = function exportPathMap() {
    const routes = {};
    routes['/'] = {
      page: '/'
    };
}
```

**Comment by Sly777** [comment]
Hey @davidsanchez96 thanks for the fix! I pushed it now.
