### ISSUE TITLE
Is there a backend to this? [Question]

### ISSUE THREAD

**Issue by noobling** [Sly777/ran#601]
Hello,

I am using your app to learn more about web technologies. I don't understand how authentication is done. It seems like it would require a backend. All I have is this GraphQL code to go off 
```jsx
mutation signinUser($email: String!, $password: String!) {
  signinUser(email: { email: $email, password: $password }) {
    token
  }
}
```
Am I correct in assuming that the backend will execute the authentication code when this query is posted to the graph cool end point?

Thanks!

**Comment by Sly777** [comment]
Normally It uses graphql mutation function for user login so It needs to have (with most of third-party graphql services have this). If you are using your own graphql, Please create signinUser mutation function on your server side. @noobling

**Comment by noobling** [comment]
So authentication is handled by Graph Cool in this case?

**Comment by Sly777** [comment]
@noobling on this example, yep

**Comment by noobling** [comment]
Thanks!
