### ISSUE TITLE
Thank you :heart:

### ISSUE THREAD

**Issue by spences10** [Sly777/ran#65]
Thank you for this!

My team and I were about to start out on a GraphCool and Next.js project and here it is :ok_hand: 

I'll be cloning it and taking a look later tonight there seems to have been a massive amount of work done already thank you so much :pray: 

Apologies if this is not the place for thanks and feel free to close the issue.

Gratitude :gift: :raised_hands:

**Comment by abattenburg** [comment]
Just wanted to echo how helpful this boilerplate has been. Thank you so much for putting all the work in and already updating!

**Comment by Sly777** [comment]
Hey @spences10 and @abattenburg,
Thanks so much for your positive comments. Honestly, It's precious for me on these days! I hope RAN can help your projects to get "better, faster, stronger." 😄
