### ISSUE TITLE
Project Schema Avaiable?

### ISSUE THREAD

**Issue by spences10** [Sly777/ran#70]
Hey @Sly777 can you add the type only Schema so it's a straight forward map to another backend?

I tried to use `get-graphql-schema ENDPOINT_URL > schema.graphql` but there was so much information in there I found it hard to drill down to just the Type only information you'd need to create a `project.graphcool` file

**Comment by Sly777** [comment]
Hey @spences10, I think it looks like not necessary on RAN for now. Because it can be different for each project so it will be not meaningful for other projects (because it depends on your graphQL data structure). I will close this issue now but If you have any different opinion or idea, please don't hesitate to write. :)

**Comment by spences10** [comment]
@Sly777 say for the user sign up/sign in which is already in the boilerplate, how am I meant to know what goes into the type for that without guessing?

I'd like to know what the types are for the existing functionality so I can build on what is already there without having to guess

**Comment by jackedgson** [comment]
Graphcool Project Schema for example project, pretty simple to create yourself:

```
type File implements Node {
  contentType: String!
  createdAt: DateTime!
  id: ID! @isUnique
  name: String!
  secret: String! @isUnique
  size: Int!
  updatedAt: DateTime!
  url: String! @isUnique
}

type User implements Node {
  createdAt: DateTime!
  email: String @isUnique
  id: ID! @isUnique
  firstName: String!
  lastName: String!
  password: String
  updatedAt: DateTime!
}

type Post implements Node {
  createdAt: DateTime!
  id: ID! @isUnique
  title: String!
  updatedAt: DateTime!
  url: String!
  votes: Int
}
```
