### ISSUE TITLE
Prettier config

### ISSUE THREAD

**Issue by spences10** [Sly777/ran#71]
Hi @Sly777 

Are there any config options available for using Prettier?

I had a look at `eslint-config-prettier` and couldn't see options for things like what I use for the VS Code extension **Prettier now**:

```json
  "prettier.singleQuote": true,
  "prettier.semi": false,
  "prettier.tabWidth": 2,
  "prettier.useTabs": false,
  "prettier.jsxSingleQuote": true,
  "prettier.flattenTernaries": true,
  "editor.formatOnSave": true,
```

Also, there doesn't seem to be a clear way to 'Prettier'ify the code or if it is it's not clear on how. Any pointers greatly appreciated.

**Comment by Sly777** [comment]
Hey @spences10, RAN is using eslint + prettier integration for code standard. For this one, It's using ```eslint-plugin-prettier``` and ```eslint-config-prettier```. These one are using default setting of prettier which is below.

```js
{
  printWidth: 80,
  tabWidth: 2,
  singleQuote: true, // except this one
  trailingComma: 'none',
  bracketSpacing: true,
  semi: true,
  useTabs: false,
  jsxBracketSameLine: false
}
```

to fix the issue with prettier, you just need to run ```yarn run lint```. It will fix all stuff. Or you can use plugins on vs code or other code editors.
