### ISSUE TITLE
Could we have the project.graphcool file please?

### ISSUE THREAD

**Issue by spences10** [Sly777/ran#77]
Hi @Sly777 

Is possible for us to have the `project.graphcool` file so we can make our own backend to reflect what you have already made here?

Using the `graphcool init --schema schema.graphql` using the provided schema here throws errors:

![image](https://user-images.githubusercontent.com/234708/28993420-d0918c42-79ad-11e7-884a-9fb6eff19c79.png)

I'm not sure if it's graphcool or the schema, either way, it's stopping me and my team from making any progress. 

Would it be possible for you to do a copy paste of the RAN `project.graphcool` file for us to use please?

**Comment by Sly777** [comment]
Hey @spences10, I think I can close this task due to talked on slack.

**Comment by spences10** [comment]
Hey @Sly777 it may be down to my lack of knowledge of GraphQL in general but we [two other team members and myself] have found this a real drain on our time trying to pick through and follow breadcrumbs on something that can be shared in a file [for Graphcool] and setup with one CLI call.

Currently, we can sign up and add a user to Graphcool backend but that's it, authentication is proving pretty hard to understand how it is done here and it's one of the main features of the bootstrap which we were hoping would take a lot of the development time out of making our app. 

Obviously you have your reasons for this which I respect but it doesn't make this a very easy to use 'bootstrap' as the backend that is in place is one that is controlled by you, if someone else wants to play around and see how things are set up they can't and have to pick through the 2,000 lines of the `schema.graphql` file to be able to set something up.

I think this question will be asked by other people as well so I'm partly confused and partly frustrated as to why you want to have this friction for someone wanting to use the bootstrap.

I really don't want to detract from all the great work you have put into this and I'm truly grateful that you have made it and it's clear that other users think it's a great resource as well

**Comment by Sly777** [comment]
Hey @spences10,

Honestly, I don't understand why you feel offended or get angry like this. Because I tried to help on slack and GitHub as well but Unfortunately, I'm not expert about the graphcool stuff so I cannot find the solution for the every problem on there. Even without expert knowledge of graphcool, I tried to help you how to figure it out. For the RAN! Problems/bugs/suggestions, I'm trying to help to all the people on my free time (because I'm not getting any money on this and I have a life like everyone :). But for the graphcool problems, if you talk with the graphcool team (which has excellent support (specially Nilan)), I think they can help on these problems. Also for the Auth system, It's just using two mutations for sign in and signup (which is one-click to create user system on graphcool). It doesn't have big messy back-end because It doesn't need. And also these are separated on the AuthField folder which has one graphQL file, one data file (redux) and one view file. As I said, I'm happy to help you but unfortunately, I cannot find the solution for the all third-party problems.

**Comment by spences10** [comment]
@sly777 I'm frustrated, I'm not offended my friend.

I know it is hard to understand the tone of something in text so please don't misconstrue this as me being angry with you, or that I think you owe me anything, you don't, I know you know this already but I want to make it clear. I write this with the utmost respect and courtesy.

You have done some awesome work, I'm not detracting from that and I am very, very grateful for the bootstrap. Thank you ❤️

I think I may have been misled with [this](https://github.com/Sly777/ran/releases/tag/0.3.0) *Authentication system is ready* implies it works with the bootstrap or have I missed something fundamental about how the bootstrap should be used? 

It's implied that this is working out of the box, I was hoping that it would be a case of making the backend and connecting then modifying for our needs from that.

Your free time (like mine) is precious and no one is paying you for this, but you love it (as do I) so I really don't want to make this something to impact on what you're doing here.

Please, please, please keep up the awesome work 💪

When we figure out what we need for the backend to be up and running with Graphcool I hope you will be willing to accept a PR with some documentation around what is needed so other not so experienced developers such as my team and I can get up and running quickly with this awesome bit of kit 👌

**Comment by BjornMelgaard** [comment]
@spences10  looking forward for documentation PR )

**Comment by jackedgson** [comment]
I too would love there to be a simple dump of the contents in the `project.graphcool` file to help get up and running with the example app or a brief walkthrough of the Graphcool setup.

**Comment by jackedgson** [comment]
Graphcool Project Schema for example project, this is what is in the `project.graphcool` file:

```
type File implements Node {
  contentType: String!
  createdAt: DateTime!
  id: ID! @isUnique
  name: String!
  secret: String! @isUnique
  size: Int!
  updatedAt: DateTime!
  url: String! @isUnique
}

type User implements Node {
  createdAt: DateTime!
  email: String @isUnique
  id: ID! @isUnique
  firstName: String!
  lastName: String!
  password: String
  updatedAt: DateTime!
}

type Post implements Node {
  createdAt: DateTime!
  id: ID! @isUnique
  title: String!
  updatedAt: DateTime!
  url: String!
  votes: Int
}
```
