### ISSUE TITLE
remote-redux-devtools failing

### ISSUE THREAD

**Issue by perminder-klair** [Sly777/ran#8]
First of all, amazing project! Thank you!

I am getting this error when running project:
```
VM9234:35 WebSocket connection to 'ws://localhost:8000/socketcluster/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
```

Fixed it by removing `port: 8000` in `composeWithDevTools` from `middleware.js` file.
Maybe will help someone with same issue.

**Comment by Sly777** [comment]
Hey @perminder-klair, Thanks for your advice! I fixed this on the new version.
