### ISSUE TITLE
Error: No available storage method found.

### ISSUE THREAD

**Issue by Matterful** [Sly777/ran#88]
Hey there!
First off, thank you for putting this together. I've been struggling a bit attempting to get this whole set up working myself - so thank you!

I don't think this is an issue with your code, but I was wondering if you are experiencing the same problem. The issue has to do with user log in. The only thing I've really changed thus far is the graph.cool URL to my own as you suggested. (thank you for introducing me to that awesome tool btw!)  So when I try to log in using the login form, the request fires off just fine and the response comes back containing a token as expected. But it seemed as though the app's state was not reflecting the "successful" login. So after digging around and logging some things, I found this error getting thrown from the localForage.js file at line 2259. Are you seeing this as well? Or is your log in working properly? I've found a few github issues on the localForage's page about something similar, but haven't found something I understand well enough to fix ... haha. 

I'm using the latest Chrome on a Mac with Sierra 10.12.6.

**Comment by Sly777** [comment]
Hey @Matterful, Thanks for your words :)

Which version of RAN are you using? You can see it from "package.json" if you don't change it. Or you can check meta tag of it. Also, can you write the error log that you get?

**Comment by Matterful** [comment]
Sorry about that. I am using RAN v0.3.1, so the version from a couple days ago. The error itself is happening silently in the background, and doesn't show up from regular logging. I first found it as I was chasing around the value of the token to see why the state wasn't getting updated. I added a console log into the reduxStore.js file just below the token variable definition on line 16. It looks like so:
`     const token = await Promise.resolve(persist.willGetAccessToken());
       console.log(`reduxStore.js, token: ${token}`);
`
As it came out through the console, this is what it looked like:
 reduxStore.js, token: Error: No available storage method found.

**Comment by Sly777** [comment]
Hey @Matterful , I'm still investigating this so I will write after found :)

**Comment by Sly777** [comment]
Hey @Matterful , I fixed it and It's on the master branch now. Can you try it please?

**Comment by Matterful** [comment]
Awesome! Thank you good sir. I will give it a shot when I get some time today and let you know how it goes :)

**Comment by GreatScot** [comment]
Hey @Sly777, I've been having the same bug.

Since you fixed it, I now see that the app state changes properly immediately after I create a new user, but if I log out, then I try to sign in again the state does not update (so I can't see the "LogOut" link in the menu for example). I can see that I get a valid token back in the response - it's just the app state doesn't update.

If more detailed information would help you just ask me whatever you need - I'm happy to provide it.

**Comment by Matterful** [comment]
Hello again!
Thank you again for working on this. I can confirm what GreatScot said. The sign up seems to work perfectly now, and logs you in correctly :) . But when just trying to sign in, the state doesn't seem to update.

**Comment by BjornMelgaard** [comment]
@Matterful @GreatScot  fixed there https://github.com/Sly777/ran/pull/100

**Comment by Sly777** [comment]
Hey @Matterful @GreatScot , I merged the changes now. It should work.

**Comment by Matterful** [comment]
Thank you good sir!

**Comment by GreatScot** [comment]
Thanks much - it's working now.
