### ISSUE TITLE
Add Flow for type checker (if the file has flow flag)

### ISSUE THREAD

**Issue by Sly777** [Sly777/ran#92]
Add Flow for type checker (if the file has flow flag)

https://flow.org/en/

#### Task rules
- It will use ```.flowconfig```
- If the file has ```flow (// @flow)``` flag, Flow will check it.
- Example pages need to get flow check

**Comment by talensjr** [comment]
Hi @Sly777, I really like your project here, and I think (and will try) to help you with this issue, if no one else is already doing it. I guess I can make a pull request along this week. 
Regards and keep this work going on!

**Comment by Sly777** [comment]
Hey @talensjr, Sure you can work on this! I'm working on another part of RAN so you are free to work  :)

**Comment by Sly777** [comment]
#319 is in progress

**Comment by talensjr** [comment]
@Sly777 Hi! I commented on the issue, I think it's ready to merge now, but there is some failure with CI, should I have to do something? 
Thanks!
