### ISSUE TITLE
Logo for RAN!

### ISSUE THREAD

**Issue by Sly777** [Sly777/ran#97]
Logo for RAN! :)

Honestly, I have no experience on a design stuff so I need help on this.

**Comment by Sly777** [comment]
![onlinelogomaker-082617-0159-1619](https://user-images.githubusercontent.com/694940/29736531-6ab509e8-8a02-11e7-8e61-66e5ea4e29b8.png)

What do you think?? @BjornMelgaard @astenmies

**Comment by BjornMelgaard** [comment]
I think it much better than my logo, which was made in first logo service found in google)

**Comment by Sly777** [comment]
#136
